apiVersion: v2
name: api-service
description: A Helm chart for the API service microservice
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - api
  - microservice
  - rest
maintainers:
  - name: hammadhaqqani
home: https://github.com/hammadhaqqani/kubernetes-gitops-blueprint
sources:
  - https://github.com/hammadhaqqani/kubernetes-gitops-blueprint
