apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: microservices
  source:
    repoURL: https://github.com/hammadhaqqani/kubernetes-gitops-blueprint
    targetRevision: main
    path: helm-charts/redis
    helm:
      releaseName: redis
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: microservices-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
